### PR TITLE
fix #62: also run tests inherited from [abstract] base classes

### LINKED ISSUE #62: Inherited tests from (abstract) base classes are not run
When having one or more (abstract) base classes along the inheritance chain, tests defined in these base classes will not be executed, e.g.

```
abstract class AbstractTestBase {

  @test "test from abstract base but it is never run"() {
     // some assertion
  }
}

@suite
class ConcreteTest extends AbstractTestBase {

  @test "test from concrete class is run"() {
     // some assertion
  }
}
```

I have implemented a PR for this and will provide it to you shortly.

### PR DESCRIPTION
**Pull request by silkentrance**
TODO

- [x] implement feature
- [x] implement tests
- [x] fix tests that fail due to local path  #issues
- [x] fix tests that fail due to a mismatch of empty lines in the expected vs. actual on ts5/ts6 resulting from stack trace elimination
- [x] FUTURE: requires further investigation into mocha's hierarchical contexts and before/after actions

~existing failing tests are unrelated and caused by duplicate declarations in the typescript .d.ts files by both ``@types/mocha`` and mocha-typescript. There is an issue and a PR for this, see #61 and #64.~

### CODE REVIEW

**Comment by silkentrance** [comment]
I also vamped up the data driven testing thing a little bit so that we can now get the output on each test run in case that the expected output does not match the actual output.

**Comment by pana-cc** [comment]
Hi @silkentrance,
I've merged the type fixes and re-triggered the Travis CI.

I would only ask you to add a few words in the readme.md about inheritance and that test methods in base classes will execute in derived classes, then the PR will be good for merge.

Thank you very much for your contribution! I would be happy to add you as a contributor to the repo. I don't have much time to tackle issues here lately, but also it is not like the project generates much support. If you have other features in mind I'd be happy to have someone pushing this project forward.

**Comment by silkentrance** [comment]
@pana-cc thank you for the feedback. i will update the readme accordingly. as for the contributor role, i will gladly step in, provided that i find the time 👍

**Comment by silkentrance** [comment]
@pana-cc not ready yet. i just found out that mocha is keeping a hierarchy of contexts, of course. maybe we can reuse this instead of chaining the calls to super.

**Comment by silkentrance** [comment]
@pana-cc i will try to tackle the remaining issue with before/after actions, both static and instance, in a future PR. so for my part this is in the green...

**Comment by silkentrance** [comment]
@pana-cc thank you very much.

**Pull request merged**
