### PR TITLE
fix #109: add appveyor as ci

### LINKED ISSUE #109: Appveyor Builds
I wonder whether we could appveyor to the mix. Travis is very good, but most users are likely to be using the Windows platform.

@pana-cc is it possible to add appveyor? AFAIK, for open source projects this is free of any charge.

### PR DESCRIPTION
**Pull request by silkentrance**

### CODE REVIEW

**Comment by silkentrance** [comment]
Perhaps you can create a project on appveyor yourself and also configure the required hooks in github?

https://ci.appveyor.com/project/silkentrance/mocha-typescript

**Comment by silkentrance** [comment]
All tests are failing, but this was to be expected 😁

**Comment by silkentrance** [comment]
1. it seems the timeouts set in the various tests (10ms) are too fast for the windows platform 😁 
2. AbstractSuiteITBase was broken: we must be calling _mocha directly instead of with node. Also, on win32, this has to be _mocha.cmd.

**Comment by silkentrance** [comment]
Oh how I hate this win32 platform:

```
AssertionError: Unexpected output on line '1'. Expected: '✓ one' to be contained in '√ one': expected false to be true
```

One would expect that all OS use the same unicode standard by now...

**Comment by silkentrance** [comment]
@pana-cc do you have any ideas on how to fix this "encoding" problem?

**Comment by silkentrance** [comment]
Oh how I hate premature work arounds for problems arising from the win32 platform:

https://github.com/mochajs/mocha/pull/641

They actually output a different set of characters depending on the os.platform() mocha is running on.

It seems as if we need to supply different expected.txt's whenever we expect '✓' as on windows it will output '√' instead. Similarly so for the failed test where we would expect '✖', on windows it will be 'x'. Small dots, whatever these are being used for, are also a potential problem...

**Comment by silkentrance** [comment]
It seems as if npm -i tgz is failing on windows is not installing anything. Maybe the path is borked.

**Comment by silkentrance** [comment]
It will fail here:

```
[00:01:48] npm verb link bins [ { 'mocha-typescript-watch': './bin/watch.js' },
[00:01:48] npm verb link bins   'C:\\projects\\mocha-typescript\\test\\it\\fixtures\\packages\\custom-ui\\node_modules\\.bin',
[00:01:48] npm verb link bins   false ]
```

**Comment by silkentrance** [comment]
It basically boils down to that the current watcher script is not able to be run under windows...

**Comment by silkentrance** [comment]
I think that we have to reimplement the watcher script so that it will be plain javascript, as in 

https://github.com/mochajs/mocha/tree/master/bin

**Comment by silkentrance** [comment]
Having fixed the issue with the failing watcher script, it will now fail on 

```
[00:03:16]       +Error: invalid interface "mocha-typescript"
```

**Comment by silkentrance** [comment]
It seems, however, that be builds on node > 6 are just fine... investigating.

**Comment by silkentrance** [comment]
I removed the node6 build from the matrix and everything is fine now.

So, for our tests, we need to use node>6 in order to have them succeed, while the software itself might still be working fine with node6.

What a waste of time on my behalf.

**Comment by silkentrance** [comment]
@pana-cc We still need to make sure that the new watch script works as expected, though.
How can we do that? Even automate a test for this?

**Comment by pana-cc** [comment]
There are not tests for the watcher. Basically we can add a test that creates a temporary directory with some simple tests, then runs the watcher on that temp dir, asserts some stuff on the watcher process output, then save a new test file in the temp directory, asserts again that file change was detected and tests were re-run.

I think I can help with a watcher tests. By the look of it you have done a good job of the rest of the issues. Is there anything else I can help with?

Thank you for all the effort.

**Comment by silkentrance** [comment]
Tests are now working and failing, as one expect them to. We must get rid of the redundant tsdd(), see #120 .

**Comment by silkentrance** [comment]
Since all builds a clean, I will merge this right away.

**Pull request merged**
