### PR TITLE
chore #115: refactor documentation

### PR DESCRIPTION
**Pull request by silkentrance**
**WORK IN PROGRESS**

@pana-cc I'd like to have your opinion on the current refactoring.

see https://github.com/pana-cc/mocha-typescript/tree/gh-115 for the refactored documentation.

**TODO**

 - [ ] API
 - [ ] ...?

**NOTES**

- the absolute links are necessary since we want this to work on npmjs.com
- currently, these links point to the feature branch and will be updated to point to master as soon as this gets approved

### CODE REVIEW

**Comment by pana-cc** [comment]
I love it!
I think we can also make a gihub page out of it.

**Comment by pana-cc** [comment]
Can we merge the docs change into the master?

**Comment by pana-cc** [comment]
We now have a domain, redirected to the docs, for example: http://mocha-typescript.org/di

**Comment by silkentrance** [comment]
@pana-cc Uh oh, well, I was still working on this. I will create another PR for that then 👍

**Comment by silkentrance** [comment]
@pana-cc The front page is missing the Further Reading links that will lead the user to more in depth documentation.

**Pull request merged**
